---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  # roles:

  tasks:
    - name: Setup Zsh
      import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - name: Setup Neovim
      import_tasks: tasks/nvim-setup.yml
      tags: ['neovim']
