---
- name: Install neovim from pacman repo
  package:
    name:
      - neovim
    state: present
  become: true

- name: install dependencies for neovim setup
  package:
    name:
      - ripgrep
      - fd
    state: present
  become: true
